### ISSUE TITLE
which yaml should i use for testing the performance of waymo pre-trained model 

### ISSUE THREAD

**Issue by bobocode** [VDIGPKU/BEV-MAE#3]
when i use cfgs/waymo_models/bevmae_waymo_voxel_20ep.yaml
it thows error:
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 89, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=demo_dataset)
  File "/bev/work/OpenPCDet/pcdet/models/__init__.py", line 17, in build_network
    model = build_detector(
  File "/bev/work/OpenPCDet/pcdet/models/detectors/__init__.py", line 42, in build_detector
    model = __all__[model_cfg.NAME](
KeyError: 'BEV_MAE'

when i use  cfgs/waymo_models/bevmae_waymo_voxel_20ep_dbscan.yaml
it thorws error:
2024-08-27 06:10:01,439   INFO  -----------------Quick Demo of OpenPCDet-------------------------
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 83, in main
    demo_dataset = DemoDataset(
  File "demo.py", line 33, in __init__
    super().__init__(
  File "/bev/work/OpenPCDet/pcdet/datasets/dataset.py", line 34, in __init__
    self.data_processor = DataProcessor(
  File "/bev/work/OpenPCDet/pcdet/datasets/processor/data_processor.py", line 76, in __init__
    cur_processor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
AttributeError: 'DataProcessor' object has no attribute 'transform_points_to_voxels_dbscan'

If i use cfgs/waymo_models/centerpoint_2xlr.yaml  or cfgs/waymo_models/centerpoint.yaml 
it throws error:
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 94, in main
    for idx, data_dict in enumerate(demo_dataset):
  File "demo.py", line 59, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/bev/work/OpenPCDet/pcdet/datasets/dataset.py", line 206, in prepare_data
    data_dict = self.point_feature_encoder.forward(data_dict)
  File "/bev/work/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 29, in forward
    data_dict['points'], use_lead_xyz = getattr(self, self.point_encoding_config.encoding_type)(
  File "/bev/work/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 48, in absolute_coordinates_encoding
    assert points.shape[-1] == len(self.src_feature_list)
AssertionError

**Comment by bobocode** [comment]
environment issue
